# Generated by Django 4.2 on 2023-04-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
    ]
