# Generated by Django 4.2 on 2023-04-29 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0003_alter_dish_description_alter_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('user', 'meal')},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='date',
        ),
    ]
