# Generated by Django 4.2 on 2023-04-30 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0005_remove_dish_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dish',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('user', 'category')},
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.dish')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='menu.ingredient')),
            ],
            options={
                'verbose_name': 'Состав блюда',
                'verbose_name_plural': 'Составы блюд',
            },
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meal',
        ),
    ]
