# Generated by Django 4.2 on 2023-04-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menu_unique_together_remove_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishingredient',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='dishingredient',
            name='ingredients',
            field=models.ManyToManyField(to='menu.ingredient'),
        ),
    ]
