# Generated by Django 4.2 on 2023-04-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_remove_dishingredient_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishingredient',
            old_name='quantity',
            new_name='portion',
        ),
    ]
