# Generated by Django 4.2 on 2023-04-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_rename_quantity_dishingredient_portion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='menu.ingredient'),
        ),
        migrations.DeleteModel(
            name='DishIngredient',
        ),
    ]
