# Generated by Django 4.2 on 2023-04-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_dish_ingredients_delete_dishingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
    ]
