# Generated by Django 4.2 on 2023-04-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menu_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='portion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
