# Generated by Django 4.2 on 2023-04-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menu_portion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='menu.ingredient'),
        ),
    ]
